// Task-oriented teams ("Coder", "Kontent", ...). Departments say where an
// agent sits; teams say which agents and skills to hand a kind of job to,
// in which role. Order inside `members` is the default role order; the
// benchmark (scripts/benchmark.mjs) adds measured speed and quality.

export const TEAMS = [
  {
    id: 'coder',
    emoji: '💻',
    color: '#4f86f7',
    name: { uz: 'Dasturchilar (Coder)', en: 'Coders' },
    best: {
      uz: 'Veb-sayt va ilovalarni boshidan oxirigacha quradi: reja, maʼlumotlar bazasi, backend, frontend, test va xavfsizlik tekshiruvi.',
      en: 'Builds websites and apps end to end: plan, database, backend, frontend, tests and a security pass.',
    },
    keywords: 'sayt veb web website app ilova dastur backend frontend baza database api kod code bug xato react node python landing platforma tizim',
    members: [
      ['agent:ecc:planner', { uz: 'Reja tuzuvchi', en: 'Planner' }],
      ['agent:ecc:architect', { uz: 'Arxitektor', en: 'Architect' }],
      ['agent:ecc:database-reviewer', { uz: 'Maʼlumotlar bazasi', en: 'Database' }],
      ['agent:claude-skills:cs-backend-engineer', { uz: 'Backend', en: 'Backend' }],
      ['agent:claude-skills:cs-frontend-engineer', { uz: 'Frontend', en: 'Frontend' }],
      ['agent:claude-skills:cs-fullstack-engineer', { uz: 'Fullstack', en: 'Fullstack' }],
      ['agent:ecc:tdd-guide', { uz: 'Test (QA)', en: 'Tests (QA)' }],
      ['agent:ecc:code-reviewer', { uz: 'Kod sharhi', en: 'Code review' }],
      ['agent:ecc:security-reviewer', { uz: 'Xavfsizlik', en: 'Security' }],
      ['agent:agent-skills:test-engineer', { uz: 'Test muhandisi', en: 'Test engineer' }],
      ['agent:agent-skills:web-performance-auditor', { uz: 'Tezlik auditi', en: 'Web performance' }],
    ],
    skills: [
      'skill:claude-skills:senior-fullstack', 'skill:claude-skills:senior-frontend', 'skill:claude-skills:senior-backend',
      'skill:claude-skills:database-schema-designer', 'skill:ecc:api-design', 'skill:ecc:frontend-patterns', 'skill:ecc:backend-patterns',
      'skill:claude-skills:saas-scaffolder', 'skill:claude-skills:landing-page-generator', 'skill:ecc:tdd-workflow', 'skill:ecc:e2e-testing', 'skill:ecc:security-review', 'skill:agent-skills:spec-driven-development', 'skill:agent-skills:frontend-ui-engineering', 'skill:agent-skills:test-driven-development', 'skill:agent-skills:incremental-implementation'],
    test: 'O‘quvchilardan test oladigan kichik veb-sayt uchun qisqa texnik reja tuz: sahifalar, maʼlumotlar bazasi jadvallari va API endpointlar.',
  },
  {
    id: 'content',
    emoji: '✍️',
    color: '#ff7a45',
    name: { uz: 'Kontent va SMM', en: 'Content & SMM' },
    best: {
      uz: 'Instagram/Telegram akkauntlarini skrinshotdan tahlil qiladi, uslubni aniqlaydi, kontent reja va tayyor postlar yozadi.',
      en: 'Analyses Instagram/Telegram accounts from screenshots, extracts the style and writes content plans and ready posts.',
    },
    keywords: 'instagram telegram tiktok youtube reels post kontent content smm blog uslub stil caption hashtag obunachi followers akkaunt kanal story sarlavha',
    members: [
      ['agent:claude-skills:cs-content-creator', { uz: 'Kontent yaratuvchi', en: 'Content creator' }],
      ['agent:claude-skills:content-strategist', { uz: 'Kontent strateg', en: 'Content strategist' }],
      ['agent:claude-skills:cs-growth-strategist', { uz: 'O‘sish strategi', en: 'Growth strategist' }],
      ['agent:ecc:marketing-agent', { uz: 'Marketolog', en: 'Marketer' }],
      ['agent:claude-skills:cs-linkedin-editor', { uz: 'Muharrir', en: 'Editor' }],
      ['agent:ecc:seo-specialist', { uz: 'SEO', en: 'SEO' }],
      ['agent:agents-500:social-media-agent', { uz: 'SMM generator', en: 'Social posts' }],
    ],
    skills: [
      'skill:claude-skills:social-media-analyzer', 'skill:claude-skills:social-media-manager', 'skill:claude-skills:social-content',
      'skill:claude-skills:content-strategy', 'skill:claude-skills:content-creator', 'skill:claude-skills:copywriting', 'skill:claude-skills:content-humanizer',
      'skill:hermes:social-media-content-calendar', 'skill:ecc:brand-voice', 'skill:ecc:content-engine', 'skill:claude-skills:video-content-strategist', 'skill:ecc:crosspost',
    ],
    test: 'Men ingliz tili o‘qituvchisiman va Instagram’da blog boshlayapman. 7 kunlik kontent reja tuz: har kun uchun format, mavzu va birinchi jumla (hook).',
  },
  {
    id: 'design',
    emoji: '🎨',
    color: '#ef6f9a',
    name: { uz: 'Dizayn va UX', en: 'Design & UX' },
    best: {
      uz: 'Interfeys va foydalanuvchi tajribasini loyihalaydi: ranglar, shriftlar, sahifa tuzilmasi, qulaylik (a11y).',
      en: 'Designs interfaces and UX: colour, type, page structure and accessibility.',
    },
    keywords: 'dizayn design ui ux interfeys rang shrift logo brend brand maket figma chiroyli qulay',
    members: [
      ['agent:best-practice:ux-designer', { uz: 'UX dizayner', en: 'UX designer' }],
      ['agent:claude-skills:cs-ux-researcher', { uz: 'UX tadqiqotchi', en: 'UX researcher' }],
      ['agent:ecc:a11y-architect', { uz: 'Qulaylik (a11y)', en: 'Accessibility' }],
      ['agent:best-practice:presentation-vibe-coding', { uz: 'Taqdimot', en: 'Presentations' }],
    ],
    skills: [
      'skill:claude-skills:ui-design-system', 'skill:claude-skills:design-system', 'skill:claude-skills:epic-design', 'skill:hermes:impeccable',
      'skill:hermes:popular-web-designs', 'skill:hermes:claude-design', 'skill:ecc:frontend-design-direction', 'skill:claude-skills:brand-guidelines', 'skill:claude-skills:a11y-audit',
    ],
    test: 'Onlayn test platformasining bosh sahifasi uchun UI tavsiya ber: ranglar, shriftlar va bloklar tartibi.',
  },
  {
    id: 'marketing',
    emoji: '📣',
    color: '#f5a524',
    name: { uz: 'Marketing va SEO', en: 'Marketing & SEO' },
    best: {
      uz: 'Reklama, landing sahifa, SEO, email ketma-ketliklar va mahsulotni ishga tushirish rejasi.',
      en: 'Ads, landing pages, SEO, email sequences and launch plans.',
    },
    keywords: 'marketing reklama ads seo google landing sotuv mijoz lead email kampaniya launch narx pricing brend promo',
    members: [
      ['agent:claude-skills:cs-demand-gen-specialist', { uz: 'Talab generatsiyasi', en: 'Demand gen' }],
      ['agent:claude-skills:growth-marketer', { uz: 'Growth marketolog', en: 'Growth marketer' }],
      ['agent:ecc:seo-specialist', { uz: 'SEO', en: 'SEO' }],
      ['agent:claude-skills:cs-aeo', { uz: 'AI qidiruv (AEO)', en: 'AEO' }],
      ['agent:claude-skills:cs-landing', { uz: 'Landing sahifa', en: 'Landing pages' }],
    ],
    skills: [
      'skill:claude-skills:seo-audit', 'skill:claude-skills:paid-ads', 'skill:claude-skills:page-cro', 'skill:claude-skills:launch-strategy',
      'skill:claude-skills:email-sequence', 'skill:claude-skills:pricing-strategy', 'skill:ecc:marketing-campaign', 'skill:claude-skills:aeo',
    ],
    test: 'Yangi onlayn ingliz tili kursi uchun 3 ta reklama g‘oyasi va landing sahifa uchun 3 ta sarlavha yoz.',
  },
  {
    id: 'research',
    emoji: '🔬',
    color: '#26b5ce',
    name: { uz: 'Tahlil va tadqiqot', en: 'Research & analysis' },
    best: {
      uz: 'Bozor, raqobatchilar va mavzular bo‘yicha chuqur tahlil, hisobot va xulosalar.',
      en: 'Deep research on markets, competitors and topics, with reports and conclusions.',
    },
    keywords: 'tahlil analiz research tadqiqot bozor raqobat trend hisobot statistika solishtir internet qidir izla yangilik twitter reddit youtube github',
    members: [
      ['agent:claude-skills:cs-deep-research', { uz: 'Chuqur tadqiqot', en: 'Deep research' }],
      ['agent:claude-skills:cs-research', { uz: 'Tadqiqotchi', en: 'Researcher' }],
      ['agent:claude-skills:cs-product-analyst', { uz: 'Mahsulot tahlilchisi', en: 'Product analyst' }],
      ['agent:claude-skills:cs-dossier', { uz: 'Dossye', en: 'Dossier' }],
      ['agent:graphify:graphify-librarian', { uz: 'Bilim grafi', en: 'Knowledge graph' }],
      ['agent:agent-reach:reach-scout', { uz: 'Internet skauti', en: 'Internet scout' }],
      ['agent:agents-500:web-research-agent', { uz: 'Veb tadqiqotchi', en: 'Web researcher' }],
      ['agent:agents-500:competitive-analysis-agent', { uz: 'Raqobat tahlili', en: 'Competitor analysis' }],
      ['agent:agents-500:data-analysis-agent', { uz: 'Data tahlilchi', en: 'Data analyst' }],
    ],
    skills: [
      'skill:claude-skills:deep-research', 'skill:claude-skills:market-research', 'skill:claude-skills:competitive-teardown',
      'skill:claude-skills:research-summarizer', 'skill:claude-skills:autoresearch-agent', 'skill:graphify:graphify', 'skill:ecc:market-research',
      'skill:agent-reach:agent-reach', 'skill:agent-reach:reach-search', 'skill:agent-reach:reach-web', 'skill:agent-reach:reach-social', 'skill:graphify:graphify-query',
    ],
    test: 'O‘zbekistonda onlayn taʼlim bozorining 5 ta asosiy trendi haqida qisqa tahlil yoz. Taxminlaringni alohida belgila.',
  },
  {
    id: 'business',
    emoji: '💼',
    color: '#46a758',
    name: { uz: 'Biznes va moliya', en: 'Business & finance' },
    best: {
      uz: 'Biznes strategiya, moliyaviy hisob-kitob, narx siyosati va startap maslahatlari.',
      en: 'Business strategy, financial models, pricing and startup advice.',
    },
    keywords: 'biznes business moliya finance pul daromad foyda xarajat narx startap investitsiya strategiya reja budjet',
    members: [
      ['agent:claude-skills:cs-ceo-advisor', { uz: 'CEO maslahatchisi', en: 'CEO advisor' }],
      ['agent:claude-skills:cs-cfo-advisor', { uz: 'CFO maslahatchisi', en: 'CFO advisor' }],
      ['agent:claude-skills:cs-financial-analyst', { uz: 'Moliyaviy tahlilchi', en: 'Financial analyst' }],
      ['agent:claude-skills:solo-founder', { uz: 'Asoschi', en: 'Founder' }],
      ['agent:claude-skills:cs-bizops-orchestrator', { uz: 'Biznes operatsiyalar', en: 'BizOps' }],
      ['agent:agents-500:customer-support-agent', { uz: 'Mijozlar xizmati', en: 'Customer support' }],
      ['agent:agents-500:resume-parser-agent', { uz: 'HR / rezyume', en: 'HR / resumes' }],
    ],
    skills: [
      'skill:claude-skills:financial-analyst', 'skill:claude-skills:saas-metrics-coach', 'skill:claude-skills:pricing-strategist',
      'skill:claude-skills:founder-mode', 'skill:claude-skills:business-investment-advisor', 'skill:claude-skills:business-name-fit',
    ],
    test: 'Oyiga 10$ obunali onlayn kurs uchun unit-iqtisodiyotni misol raqamlar bilan tushuntir (CAC, LTV, oylik foyda).',
  },
  {
    id: 'education',
    emoji: '🎓',
    color: '#8d9eff',
    name: { uz: 'Taʼlim', en: 'Education' },
    best: {
      uz: 'Dars rejalari, test savollari, o‘quv dasturlari va mavzuni oddiy tilda tushuntirish.',
      en: 'Lesson plans, quizzes, syllabi and plain-language explanations.',
    },
    keywords: 'dars talaba o‘quvchi oquvchi maktab test savol imtihon kurs taʼlim talim o‘qituvchi ustoz syllabus mavzu tushuntir',
    members: [
      ['agent:claude-skills:cs-syllabus', { uz: 'O‘quv dasturi', en: 'Syllabus' }],
      ['agent:claude-skills:cs-deep-learning-tutor', { uz: 'Repetitor', en: 'Tutor' }],
      ['agent:claude-skills:cs-claude-coach', { uz: 'Murabbiy', en: 'Coach' }],
    ],
    skills: ['skill:claude-skills:syllabus', 'skill:hermes:memento-flashcards', 'skill:claude-skills:deep-learning-book', 'skill:claude-skills:claude-coach'],
    test: '9-sinf matematikasidan “kvadrat tenglamalar” mavzusida 5 ta test savoli tuz (4 variant, to‘g‘ri javob va qisqa izoh bilan).',
  },
  {
    id: 'security',
    emoji: '🛡️',
    color: '#e5484d',
    name: { uz: 'Xavfsizlik', en: 'Security' },
    best: {
      uz: 'Kod va tizim xavfsizligi, maxfiylik (GDPR), audit va muvofiqlik tekshiruvlari.',
      en: 'Code and system security, privacy (GDPR), audits and compliance checks.',
    },
    keywords: 'xavfsizlik security parol login himoya hujum audit gdpr maxfiylik token shifrlash',
    members: [
      ['agent:ecc:security-reviewer', { uz: 'Xavfsizlik sharhi', en: 'Security review' }],
      ['agent:claude-skills:cs-ciso-advisor', { uz: 'CISO', en: 'CISO' }],
      ['agent:claude-skills:cs-compliance-officer', { uz: 'Muvofiqlik', en: 'Compliance' }],
      ['agent:claude-skills:cs-dpo-gdpr', { uz: 'Maxfiylik (GDPR)', en: 'Privacy (GDPR)' }],
      ['agent:agent-skills:security-auditor', { uz: 'Xavfsizlik auditori', en: 'Security auditor' }],
    ],
    skills: ['skill:ecc:security-review', 'skill:claude-skills:senior-security', 'skill:claude-skills:security-pen-testing', 'skill:claude-skills:gdpr-dsgvo-expert', 'skill:claude-skills:cloud-security', 'skill:agent-skills:security-and-hardening'],
    test: 'Oddiy login formasi uchun eng muhim 5 ta xavfsizlik tekshiruvini qisqa sanab ber.',
  },
  {
    id: 'devops',
    emoji: '☁️',
    color: '#5aa9e6',
    name: { uz: 'DevOps va server', en: 'DevOps & hosting' },
    best: {
      uz: 'Saytni serverga joylash, Docker, CI/CD, domen va monitoring.',
      en: 'Deploying sites, Docker, CI/CD, domains and monitoring.',
    },
    keywords: 'server deploy joylash hosting vps docker domen ci cd github actions nginx linux monitoring',
    members: [
      ['agent:claude-skills:devops-engineer', { uz: 'DevOps muhandis', en: 'DevOps engineer' }],
      ['agent:ecc:build-error-resolver', { uz: 'Build xatolari', en: 'Build fixer' }],
      ['agent:ecc:homelab-architect', { uz: 'Infratuzilma', en: 'Infrastructure' }],
      ['agent:ecc:network-architect', { uz: 'Tarmoq', en: 'Network' }],
    ],
    skills: ['skill:ecc:deployment-patterns', 'skill:ecc:docker-patterns', 'skill:claude-skills:ci-cd-pipeline-builder', 'skill:claude-skills:observability-designer', 'skill:hermes:cloudflare-temporary-deploy'],
    test: 'Node.js + SQLite veb-ilovani oddiy VPS serverga joylash uchun qisqa qadamlar ro‘yxatini ber.',
  },
  {
    id: 'product',
    emoji: '🗺️',
    color: '#c9a227',
    name: { uz: 'Mahsulot va loyiha', en: 'Product & projects' },
    best: {
      uz: 'Mahsulot g‘oyasini MVP, funksiyalar ro‘yxati, prioritetlar va sprint rejalariga aylantiradi.',
      en: 'Turns an idea into an MVP, feature list, priorities and sprint plans.',
    },
    keywords: 'mahsulot product mvp funksiya feature prioritet roadmap loyiha project sprint reja talab',
    members: [
      ['agent:claude-skills:cs-product-manager', { uz: 'Mahsulot menejeri', en: 'Product manager' }],
      ['agent:claude-skills:cs-product-strategist', { uz: 'Mahsulot strategi', en: 'Product strategist' }],
      ['agent:claude-skills:cs-agile-product-owner', { uz: 'Product owner', en: 'Product owner' }],
      ['agent:claude-skills:cs-project-manager', { uz: 'Loyiha menejeri', en: 'Project manager' }],
    ],
    skills: ['skill:claude-skills:agile-product-owner', 'skill:claude-skills:code-to-prd', 'skill:claude-skills:roadmap-communicator', 'skill:claude-skills:product-research', 'skill:claude-skills:ux-researcher-designer', 'skill:agent-skills:interview-me', 'skill:agent-skills:idea-refine', 'skill:agent-skills:planning-and-task-breakdown'],
    test: 'O‘quvchilar uchun onlayn test platformasining MVP funksiyalari va ularning prioritetlarini tuz.',
  },
  {
    id: 'office',
    emoji: '🏢',
    color: '#d97757',
    name: { uz: 'Ofis va umumiy', en: 'Office & general' },
    best: {
      uz: 'Salomlashish, umumiy savollar, vazifani to‘g‘ri jamoaga yo‘naltirish va yakuniy hisobot.',
      en: 'Greetings, general questions, routing work to the right team and final reports.',
    },
    keywords: 'salom assalomu alaykum hello hi qalay ahvol rahmat yordam kim nima',
    members: [
      ['agent:claude-office:office-manager', { uz: 'Ofis menejeri', en: 'Office manager' }],
      ['agent:hermes:hermes', { uz: 'Universal yordamchi', en: 'Generalist' }],
      ['agent:claude-skills:cs-chief-of-staff', { uz: 'Shtab boshlig‘i', en: 'Chief of staff' }],
      ['agent:agents-500:meeting-notes-agent', { uz: 'Majlis bayonnomasi', en: 'Meeting notes' }],
      ['agent:agents-500:email-drafting-agent', { uz: 'Xat yozuvchi', en: 'Email drafts' }],
    ],
    skills: ['skill:claude-skills:research-summarizer', 'skill:graphify:graphify'],
    test: 'Salom hammaga, ahvollar qalay? O‘zingni qisqa tanishtir va menga qanday ishlarda eng yaxshi yordam bera olishingni ayt.',
  },
];
